# Generated by Django 4.2.5 on 2023-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(null=True, related_name='projects_contributed_to', to='API.contributor'),
        ),
    ]
