# Generated by Django 4.2.5 on 2023-10-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_issue_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigne_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_assignees', to='API.contributor'),
        ),
    ]
