# Generated by Django 4.2.5 on 2023-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('API', '0006_alter_issue_assigne_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects_contributed_to', to='API.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques à cet utilisateur.', related_name='custom_user_permissions', to='auth.permission', verbose_name='permissions de l’utilisateur'),
        ),
    ]
